### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by std-crtor** [Nebula4869/YOLOv5-LibTorch#1]
//I use the way of torch.jit.trace to convert original pt file to torchscript pt file  , but it generates many bugs.....
I find it !! There is a export.py file converting original pt file to torchscript pt file in the YOLOv5 project .

**Comment by Nebula4869** [comment]
from this repo&nbsp;https://github.com/ultralytics/yolov5 you can use the "export.py" to generate onnx and libtorch model.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nebula4869/YOLOv5-LibTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月1日(星期四) 上午10:56
收件人:&nbsp;"Nebula4869/YOLOv5-LibTorch"<YOLOv5-LibTorch@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Nebula4869/YOLOv5-LibTorch] I need help! (#1)





 
could you provide the ways of generating yolov5s.torchscript.pt , because i find the original file yolov5s.pt could not be used in C++, but yolov5s.torchscript.pt works in C++ !!!
 I use the way of torch.jit.trace to convert original pt file to torchscript pt file  , but it generates many bugs.....

**Comment by Yasin40** [comment]
> from this repo&nbsp;https://github.com/ultralytics/yolov5 you can use the "export.py" to generate onnx and libtorch model.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nebula4869/YOLOv5-LibTorch" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月1日(星期四) 上午10:56 收件人:&nbsp;"Nebula4869/YOLOv5-LibTorch"<YOLOv5-LibTorch@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Nebula4869/YOLOv5-LibTorch] I need help! (#1) could you provide the ways of generating yolov5s.torchscript.pt , because i find the original file yolov5s.pt could not be used in C++, but yolov5s.torchscript.pt works in C++ !!! I use the way of torch.jit.trace to convert original pt file to torchscript pt file , but it generates many bugs..... — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I tried by this repo and export.py, but got some error in c++ and warning in python output of this script, described [here](https://github.com/ultralytics/yolov5/issues/1554#issue-753020980)
Please help me!

**Comment by Nebula4869** [comment]
I don't know what's wrong with your code but have you set "model.model[-1].export = False" in export.py? or you can try using a previous version of yolov5 repo, the author may have update some details in the network.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nebula4869/YOLOv5-LibTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月30日(星期一) 下午4:33
收件人:&nbsp;"Nebula4869/YOLOv5-LibTorch"<YOLOv5-LibTorch@noreply.github.com&gt;;
抄送:&nbsp;"Nebula"<nebula4869@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Nebula4869/YOLOv5-LibTorch] I need help! (#1)





  
from this repo&nbsp;https://github.com/ultralytics/yolov5 you can use the "export.py" to generate onnx and libtorch model.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nebula4869/YOLOv5-LibTorch" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月1日(星期四) 上午10:56 收件人:&nbsp;"Nebula4869/YOLOv5-LibTorch"<YOLOv5-LibTorch@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Nebula4869/YOLOv5-LibTorch] I need help! (#1) could you provide the ways of generating yolov5s.torchscript.pt , because i find the original file yolov5s.pt could not be used in C++, but yolov5s.torchscript.pt works in C++ !!! I use the way of torch.jit.trace to convert original pt file to torchscript pt file , but it generates many bugs..... — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
I tried by this repo and export.py, but got some error in c++ and warning in python output of this script, described here
 Please help me!

**Comment by Yasin40** [comment]
> I don't know what's wrong with your code but have you set "model.model[-1].export = False" in export.py? or you can try using a previous version of yolov5 repo, the author may have update some details in the network.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nebula4869/YOLOv5-LibTorch" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月30日(星期一) 下午4:33 收件人:&nbsp;"Nebula4869/YOLOv5-LibTorch"<YOLOv5-LibTorch@noreply.github.com&gt;; 抄送:&nbsp;"Nebula"<nebula4869@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Nebula4869/YOLOv5-LibTorch] I need help! (#1) from this repo&nbsp;https://github.com/ultralytics/yolov5 you can use the "export.py" to generate onnx and libtorch model. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nebula4869/YOLOv5-LibTorch" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月1日(星期四) 上午10:56 收件人:&nbsp;"Nebula4869/YOLOv5-LibTorch"<YOLOv5-LibTorch@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[Nebula4869/YOLOv5-LibTorch] I need help! (#1) could you provide the ways of generating yolov5s.torchscript.pt , because i find the original file yolov5s.pt could not be used in C++, but yolov5s.torchscript.pt works in C++ !!! I use the way of torch.jit.trace to convert original pt file to torchscript pt file , but it generates many bugs..... — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. I tried by this repo and export.py, but got some error in c++ and warning in python output of this script, described here Please help me! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for attention. Yes, i try with this change and test v5.3.0 and latest , but got error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/models/yolo.py", line 45, in forward
    _35 = (_4).forward(_34, )
    _36 = (_2).forward((_3).forward(_35, ), _29, )
    _37 = (_0).forward(_33, _35, (_1).forward(_36, ), )
           ~~~~~~~~~~~ <--- HERE
    _38, _39, _40, _41, = _37
    return (_41, [_38, _39, _40])
  File "code/__torch__/models/yolo.py", line 75, in forward
    _52 = torch.sub(_51, CONSTANTS.c2, alpha=1)
    _53 = torch.to(CONSTANTS.c3, dtype=6, layout=0, device=torch.device("cpu"), pin_memory=False, non_blocking=False, copy=False, memory_format=None)
    _54 = torch.mul(torch.add(_52, _53, alpha=1), torch.select(CONSTANTS.c4, 0, 0))
                    ~~~~~~~~~ <--- HERE
    _55 = torch.slice(y, 4, 0, 2, 1)
    _56 = torch.expand(torch.view(_54, [3, 80, 48, 2]), [1, 3, 80, 48, 2], implicit=True)

Traceback of TorchScript, original code (most recent call last):
/home/yasin/clones/pvyolo/yolov5-3.0/models/yolo.py(47): forward
/home/yasin/envs/yolo-torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py(704): _slow_forward
/home/yasin/envs/yolo-torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py(720): _call_impl
/home/yasin/clones/pvyolo/yolov5-3.0/models/yolo.py(131): forward_once
/home/yasin/clones/pvyolo/yolov5-3.0/models/yolo.py(111): forward
/home/yasin/envs/yolo-torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py(704): _slow_forward
/home/yasin/envs/yolo-torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py(720): _call_impl
/home/yasin/envs/yolo-torch1.6/lib/python3.8/site-packages/torch/jit/__init__.py(1109): trace_module
/home/yasin/envs/yolo-torch1.6/lib/python3.8/site-packages/torch/jit/__init__.py(953): trace
models/export.py(38): <module>
RuntimeError: The size of tensor a (80) must match the size of tensor b (48) at non-singleton dimension 3

```
